---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: IELTS
  description: Group description
spec:
  type: team
  profile:
    displayName: IELTS
  parent: optional-parent-group
  children: []
  members: []

---

### System entities
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ors-platform
  description: Student plcement application services.
spec:
  owner: IELTS

---
## API components

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-backoffice-bff
  description: This component has swagger definition.
  annotations:
    backstage.io/techdocs-ref: https://idpchange.atlassian.net/wiki/spaces/AAW/pages/898826491/Microservice+Customer+Profile
  tags:
    - ors-backoffice-bff-api
    - v1
spec:
  owner: IELTS
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-backoffice-bff/-/blob/develop/contracts/v1/api/openapi.yaml
