---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: IELTS
  description: Group description
spec:
  type: team
  profile:
    displayName: IELTS
  parent: optional-parent-group
  children: []
  members: []

---
## API components

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-backoffice-bff
  description: This component has swagger definition.
  annotations:
    backstage.io/techdocs-ref: https://idpchange.atlassian.net/wiki/spaces/AAW/pages/898826491/Microservice+Customer+Profile
  tags:
    - ors-backoffice-bff
    - v1
spec:
  owner: IELTS
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-backoffice-bff/-/blob/develop/contracts/v1/api/openapi.yaml
  dependsOn:
    - component:default/ors-user-profile
---

## API components

  apiVersion: backstage.io/v1alpha1
  kind: API
  metadata:
    name: ors-user-profile
    description: This component has swagger definition.
    annotations:
      backstage.io/techdocs-ref: https://idpchange.atlassian.net/wiki/spaces/AAW/pages/898826491/Microservice+Customer+Profile
    tags:
      - ors-user-profile
      - v1
  spec:
    owner: IELTS
    type: openapi
    lifecycle: development
    definition:
      $text: https://gitlab.com/idp-education/ielts/ors/ors-user-profile/-/blob/develop/contracts/v1/api/openapi.yaml
---
