---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ielts
  description: IELTS team responsible for ORS platform services
spec:
  type: team
  children: []
  members: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ors-platform
  description: ORS Platform system that includes multiple microservices
spec:
  owner: ielts

---
## API components

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-booking
  description: This component has swagger definition.
  tags:
    - ors-booking
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-booking/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-voucher-is
  description: This component has swagger definition.
  tags:
    - ors-voucher-is
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-voucher-is/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cmds-integration
  description: This component has swagger definition.
  tags:
    - cmds-integration
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/cmds-integration/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-iam
  description: This component has swagger definition.
  tags:
    - ors-iam
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-iam/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-offline-payment-is
  description: This component has swagger definition.
  tags:
    - ors-offline-payment-is
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/payment-gateways/ors-offline-payment-is/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-organisation
  description: This component has swagger definition.
  tags:
    - ors-organisation
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-organisation/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-payment
  description: This component has swagger definition.
  tags:
    - ors-payment
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-payment/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-product-catalogue
  description: This component has swagger definition.
  tags:
    - ors-product-catalogue
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-product-catalogue/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-reference-data
  description: This component has swagger definition.
  tags:
    - ors-reference-data
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-reference-data/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-result
  description: This component has swagger definition.
  tags:
    - ors-result
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-result/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-session-aggregator
  description: This component has swagger definition.
  tags:
    - ors-session-aggregator
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-session-aggregator/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-session
  description: This component has swagger definition.
  tags:
    - ors-session
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-session/-/blob/develop/contracts/v1/api/openapi.yaml


---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-terms-and-conditions
  description: This component has swagger definition.
  tags:
    - ors-terms-and-conditions
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-terms-and-conditions/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-test-centre
  description: This component has swagger definition.
  tags:
    - ors-test-centre
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-test-centre/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-user-profile
  description: This component has swagger definition.
  tags:
    - ors-user-profile
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-user-profile/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-email-integration
  description: This component has swagger definition.
  tags:
    - ors-email-integration
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-email-integration/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-icapps-integration
  description: This component has swagger definition.
  tags:
    - ors-icapps-integration
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-icapps-integration/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: oors-staff-profile
  description: This component has swagger definition.
  tags:
    - ors-staff-profile
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-staff-profile/-/blob/develop/contracts/v1/api/openapi.yaml


---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-backoffice-bff
  description: This component has swagger definition.
  annotations:
    backstage.io/techdocs-ref: https://idpchange.atlassian.net/wiki/spaces/ID1/pages/2844557626/Technical+Design+Progressive+Profile+Microservice
  tags:
    - backoffic-bff
    - v1
spec:
  owner: ielts
  type: openapi
  lifecycle: development
  definition:
    $text: https://gitlab.com/idp-education/ielts/ors/ors-backoffice-bff/-/blob/develop/contracts/v1/api/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ors-backoffice-bff
  description: This component has live application definitions.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - ors-backoffice-bff
spec:
  owner: ielts
  type: service
  lifecycle: development
  system: ors-platform
  providesApis:
    - api:default/ors-backoffice-bff
  consumesApis:
    - api:default/ors-booking
    - api:default/ors-voucher-is
    - api:default/cmds-integration
    - api:default/ors-iam
    - api:default/ors-offline-payment-is
    - api:default/ors-organisation
    - api:default/ors-payment
    - api:default/ors-product-catalogue
    - api:default/ors-reference-data
    - api:default/ors-receipt
    - api:default/ors-result
    - api:default/ors-session-aggregator
    - api:default/ors-session
    - api:default/ors-staff-profile
    - api:default/ors-terms-and-conditions
    - api:default/ors-test-centre
    - api:default/ors-user-profile
    - api:default/ors-email-integration
    - api:default/ors-icapps-integration

---
