apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-backoffice-bff
  description: Backoffice BFF API that consumes multiple microservices
  tags:
    - bff
    - backoffice
spec:
  type: openapi
  lifecycle: production
  owner: ielts
  system: ors-platform
  consumesApis:
    - cmds-integration-client-v1
    - ors-reporting-aggregator-client-v1
    - ors-booking-client-v1
    - ors-booking-client-v2
    - ors-data
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ors-booking
  description: ORS Booking Service
spec:
  type: service
  lifecycle: production
  owner: ielts
  system: ors-platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cmds-integration-client-v1
  description: CMDS Integration Client Service
spec:
  type: service
  lifecycle: production
  owner: ielts
  system: ors-platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ors-reporting-aggregator
  description: ORS Reporting Aggregator Service
spec:
  type: service
  lifecycle: production
  owner: ielts
  system: ors-platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ors-data
  description: ORS Data Service
spec:
  type: service
  lifecycle: production
  owner: ielts
  system: ors-platform
