---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ielts
  description: IELTS team responsible for ORS platform services
spec:
  type: team
  children: []
  members: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ors-platform
  description: ORS Platform system that includes multiple microservices
spec:
  owner: ielts

  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ors-backoffice-bff
  description: Backoffice BFF API that consumes multiple microservices
  tags:
    - bff
    - backoffice
spec:
  type: openapi
  lifecycle: production
  owner: ielts
  system: ors-platform
  consumesApis:
    - cmds-integration
    - ors-data

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cmds-integration
  description: CMDS Integration Client Service
spec:
  type: service
  lifecycle: production
  owner: ielts
  system: ors-platform

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ors-data
  description: ORS Data Service
spec:
  type: service
  lifecycle: production
  owner: ielts
  system: ors-platform
