---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ielts
  description: Group description
spec:
  type: team
  profile:
    displayName: IELTS
  parent: optional-parent-group
  children: []
  members: []

---

### System entities
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ors-platform
  description: Student plcement application services.
spec:
  owner: ielts

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ors-backoffice-bff
  description: Backoffice BFF API that consumes multiple microservices
  tags:
    - bff
    - backoffice
spec:
  type: openapi
  lifecycle: production
  owner: ielts
  system: ors-platform
  consumesApis:
    - cmds-integration-client-v1
    - ors-data

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cmds-integration-client-v1
  description: CMDS Integration Client Service
spec:
  type: service
  lifecycle: production
  owner: ielts
  system: ors-platform

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ors-data
  description: ORS Data Service
spec:
  type: service
  lifecycle: production
  owner: ielts
  system: ors-platform
