---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ielts
  description: IELTS team responsible for ORS platform services
spec:
  type: team
  children: []
  members: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ors-platform
  description: ORS Platform system that includes multiple microservices
spec:
  owner: ielts
